version: '3'
services:
  api:
    build: ./
    ports:
      - 7777:7777
    container_name: movies-docker-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=7777
      - MONGO_URL=/mongo:27017
    depends_on:
      - mongo
    networks:
      - movies-docker-network

  mongo:
    image: mongo:4.4.4
    container_name: movies-docker-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
    networks:
      - movies-docker-network

networks:
  movies-docker-network:
    driver: bridge
